INSERT INTO CARTEABONNES(DATEACHAT, NOM, PRENOM , AGE ,EMAIL) VALUES ('2010-12-11',
	'DODO','BA',25,'mymail@live.com');
	
INSERT INTO CARTEABONNES(DATEACHAT, NOM, PRENOM , AGE ,EMAIL) VALUES ('2010-12-11',
	'DIDO','BA',25,'myail@live.com');

INSERT INTO CARTEABONNES(DATEACHAT, NOM, PRENOM , AGE ,EMAIL) VALUES ('2010-12-11',
	'DDO','BA',25,'mmail@live.com');
	
INSERT INTO CARTEABONNES(DATEACHAT, NOM, PRENOM , AGE ,EMAIL) VALUES ('2010-12-11',
	'DAODO','BA',25,'ymail@live.com');
	
INSERT INTO CARTEABONNES(DATEACHAT, NOM, PRENOM , AGE ,EMAIL) VALUES ('2010-12-11',
	'DODO','BA',25,'bmymail@live.com');
	
INSERT INTO CARTEABONNES(DATEACHAT, NOM, PRENOM , AGE ,EMAIL) VALUES ('2010-12-11',
	'DODk','BA',25,'pmymail@live.com');
	
INSERT INTO CARTEABONNES(DATEACHAT, NOM, PRENOM , AGE ,EMAIL) VALUES ('2010-12-11',
	'KODO','BA',25,'mymail@live.com');
	
INSERT INTO CARTEABONNES(DATEACHAT, NOM, PRENOM , AGE ,EMAIL) VALUES ('2010-12-11',
	'LDODO','BA',25,'smymail@live.com');
	
INSERT INTO CARTEABONNES(DATEACHAT, NOM, PRENOM , AGE ,EMAIL) VALUES ('2010-12-11',
	'NDODO','BA',25,'moymail@live.com');
	
INSERT INTO CARTEABONNES(DATEACHAT, NOM, PRENOM , AGE ,EMAIL) VALUES ('2010-12-11',
	'IIDODO','BA',25,'plymail@live.com');