insert into FILMS (TITRE,DUREE,RESUME,DATESORTIE,ACTEUR,POPULARITE,IMAGE) values ('Mon beau-père et nous','1:38:00','Cela fait dix ans déjà que Greg Furniker,
brave infirmier expert en bourdes, a fait la rencontre de son beau-papa, Jack Byrnes, ex-agent de la CIA, colérique, soupçonneux et paranoïaque. Dix ans que chacune de leurs réunions de famille fait des étincelles, surtout lorsque les parents Furniker, des babas cool très sea, sex and fun sont là. Après une petite trêve, les doutes de Jack ressurgissent lorsque Greg, à court d’argent, travaille au noir pour un laboratoire. Celui-ci a une nouvelle mission : prouver à Jack qu’il est un vrai chef de famille, capable d’élever ses enfants. Va-t-il réussir l’examen final de Jack et lui succéder à la tête du clan… ou le cercle de confiance sera-t-il brisé pour toujours ?',
'2010-12-21','Ben Stiller, Robert De Niro et Dustin Hoffman',0.45,'img1.jpg');
insert into FILMS (TITRE,DUREE,RESUME,DATESORTIE,ACTEUR,POPULARITE,IMAGE) values('Le Monde de Narnia : L''Odyssée du Passeur d''aurore','1:54:00','Edmund et Lucy Pevensie, accompagnés de leur détestable cousin Eustache, plongent à travers un intriguant tableau et atterrissent sur le pont d''un magnifique bateau, le Passeur d’Aurore. À bord, ils retrouvent leurs amis le prince Caspian et la souris guerrière Ripitchip. Ensemble, les courageux voyageurs embarquent vers des îles mystérieuses. Affrontant des créatures magiques et de sinistres ennemis, ils seront également amenés à retrouver leur ami le grand lion Aslan.','2010-12-08','Ben Barnes, Georgie Henley, Skandar Keynes...',0.34,'img2.jpg');
insert into FILMS (TITRE,DUREE,RESUME,DATESORTIE,ACTEUR,POPULARITE,IMAGE)values('Raiponce','1:41:00','Lorsque Flynn Rider, le bandit le plus recherché du royaume, se réfugie dans une mystérieuse tour, il se retrouve pris en otage par Raiponce, une belle jeune fille à l’impressionnante chevelure de 20 mètres de long. L’étonnante geôlière de Flynn cherche un moyen de sortir de cette tour où elle est enfermée depuis des années. Elle passe alors un accord avec le séduisant brigand… C’est le début d’une aventure délirante bourrée d’action, d’humour et de sentiment, au cours de laquelle l’improbable duo va rencontrer un cheval super-flic, un caméléon à l’instinct de protection surdéveloppé et une bande de voleurs très « bruts »…','2010-12-01',
'Animation de Byron Howard et Nathan Greno avec Donna Murphy, Mandy Moore, Zachary Levi...',0.8,'img3.jpg');
insert into FILMS (TITRE,DUREE,RESUME,DATESORTIE,ACTEUR,POPULARITE,IMAGE)values('Les Emotifs anonymes','1:30:00','Brillante chocolatière, Angélique souffre de timidité maladive. Pour tenter de s’en sortir, elle s’est inscrite aux Émotifs anonymes. Une thérapie qui lui permet de trouver le courage de postuler dans une grande chocolaterie. N’osant pas dire à son patron qu’elle est experte dans la fabrication de chocolat, elle en est réduite à démarcher les magasins pour vendre les produits de l’entreprise. Elle n’est d’ailleurs pas insensible au charme de son directeur, Jean-René, lui aussi un grand introverti. Son psychiatre lui demande d’inviter sa nouvelle employée à dîner. La soirée est un désastre : submergé par ses émotions, Jean-René quitte le restaurant sans prévenir sa convive','2010-12-22','Comédie romantique de Jean-Pierre Aéris

avec Benoît Poelvoorde, Isabelle Carré, Lorella Cravotta...',0.6,'img4.jpg');
insert into FILMS (TITRE,DUREE,RESUME,DATESORTIE,ACTEUR,POPULARITE,IMAGE)values('Harry Potter et les reliques de la mort - partie 1','2:27:00','Harry Potter et ses amis, Hermione et Ron, ne se sont pas remis de la mort de leur mentor et protecteur, Dumbledore, le directeur de l’école de magie Poudlard. Ils doivent en plus faire face à Voldemort, dont le pouvoir s’accroît de jour en jour. Ce génie du mal tire son énergie et son immortalité des Horcruxes, des objets ou des créatures dans lesquels il a enfermé une partie de son âme. S’il est tué, il peut continuer à vivre à travers eux. Si certains ont déjà été détruits, il en reste suffisamment pour que le règne de Voldemort ne s’achève pas de sitôt. Harry décide alors de traquer et anéantir les Horcruxes. Hermione, Ron et le jeune sorcier ne peuvent compter que sur eux-mêmes pour y parvenir. Les forces obscures vont profiter de leur vulnérabilité pour tenter de les monter les uns contre les autres. D’autant que le monde de la sorcellerie est devenu risqué pour ceux qui s’opposent à Voldemort. Ses serviteurs, les Mangemorts, font régner la terreur et s’emparent du ministère de la Magie avant de prendre Poudlard ! Ils vont poursuivre Harry Potter sans relâche car Voldemort le veut vivant… Scindée en deux parties (le dénouement est prévu le 13 juillet 2011), l’adaptation du septième et dernier roman de J. K. Rowling raconte l’ultime combat entre Harry Potter et son ennemi juré, Lord Voldemort.','2010-11-24','Fantastique de David Yates

avec Daniel Radcliffe, Emma Watson, Rupert Grint...',0.78,'img5.jpg');
insert into FILMS (TITRE,DUREE,RESUME,DATESORTIE,ACTEUR,POPULARITE,IMAGE)values('Megamind','1:36:00','Les studios DreamWorks Animation vous présentent « Megamind », le superméchant le plus génial de toute l’histoire de l’humanité. Et le pire loser aussi...
Depuis des années, il essaie par tous les moyens de conquérir Metro City. En vain : chacune de ses tentatives est mise en échec par l’invincible Metro Man, et tourne à la farce. Jusqu’au jour où Megamind tue Metro Man ! Mais un superméchant a besoin d’un superhéros pour se sentir exister et avoir un but dans la vie. Megamind a donc l’idée de se fabriquer un nouvel adversaire : Titan, encore plus grand, plus fort et plus héroïque que le précédent.
Problème : Titan découvre vite que c’est bien plus drôle d’être un méchant que de protéger les hommes. Et encore plus amusant de détruire le monde que de le diriger… Pris au piège, Megamind réussira-t-il à vaincre sa diabolique création ? À devenir le héros inattendu de sa propre histoire ?','2010-12-15',
'Animation de Tom McGrath avec Franck Dubosc, Géraldine Nakache, Kad Merad...',57,'img6.jpg');
insert into FILMS (TITRE,DUREE,RESUME,DATESORTIE,ACTEUR,POPULARITE,IMAGE)values('The Tourist','1:43:00','Dans un train au départ de Paris et en route vers Venise, un touriste américain est totalement vampé par une sublime créature qui s’est installée en face de lui. Seulement voilà, cette rencontre merveilleuse n’est pas le fruit du hasard. La belle, Élise Clifton-Ward, est en réalité un agent d’Interpol qui a décidé d’utiliser Frank pour tromper un dangereux criminel. À Venise, pour Frank, c’est le terminus de la parenthèse enchantée. Notre homme ordinaire et sans histoire a plongé tête baissée au cœur d’une machination complexe qui va aller crescendo. Un piège qui pourrait être mortel et dont l’instigateur est un homme mystérieux…','2010-12-15',
'Thriller de Florian Henckel von Donnersmarck avec Angelina Jolie, Johnny Depp, Timothy Dalton...',89,'img7.jpg');
insert into FILMS (TITRE,DUREE,RESUME,DATESORTIE,ACTEUR,POPULARITE,IMAGE)values('Même la pluie','1:44:00','Sebastian, jeune réalisateur passionné et son producteur arrivent dans le décor somptueux des montagnes boliviennes pour entamer le tournage d''un film. Les budgets de production sont serrés et Costa, le producteur, se félicite de pouvoir employer des comédiens et des figurants locaux à moindre coût. Mais bientôt le tournage est interrompu par la révolte menée par l''un des principaux figurants contre le pouvoir en place qui souhaite privatiser l''accès à l''eau courante. Costa et Sebastian se trouvent malgré eux emportés dans cette lutte pour la survie d''un peuple démuni. Ils devront choisir entre soutenir la cause de la population et la poursuite de leur propre entreprise sur laquelle ils ont tout misé. Ce combat pour la justice va bouleverser leur existence.','2011-01-05',
'Drame de Icíar Bollaín avec Carlos Aduviri, Gael García Bernal, Luis Tosar...',34.5,'img8.jpg');
insert into FILMS (TITRE,DUREE,RESUME,DATESORTIE,ACTEUR,POPULARITE,IMAGE)values('Que justice soit faite','1:48:00','Dix ans après le meurtre de sa femme et sa fille, un homme se dresse contre le procureur en charge du procès des meurtriers, pour obtenir lui-même la justice. Sa vengeance menace tout aussi bien l''homme qui leur a accordé la clémence, que le système et la ville elle-même.','2010-12-22','Thriller de F. Gary Gray
avec Gerard Butler, Jamie Foxx, Leslie Bibb..',24,'img9.jpg');
insert into FILMS (TITRE,DUREE,RESUME,DATESORTIE,ACTEUR,POPULARITE,IMAGE)values('Inception','2:26:00','Sous la houlette de Christopher Nolan, Leonardo DiCaprio nous plonge dans l’univers des rêves. Un thriller haletant aux confins de l’esprit. As de la cambriole, Dom Cobb est passé maître dans l’art périlleux de l’extraction (inception en anglais). Une technique qui consiste à pénétrer dans les méandres de l’inconscient des gens lorsqu’ils rêvent et que leur esprit est vulnérable. Grâce à ce talent rare, Cobb est prisé dans le milieu de l’espionnage industriel mais est aussi un fugitif contraint de parcourir la planète après avoir perdu son grand amour. Bientôt on lui offre une chance de se retrouver dans sa vie antérieure. Cette fois, il ne s’agit pas de subtiliser une idée mais au contraire d’en implanter une dans l’esprit de la victime. Si Cobb et ses acolytes y parviennent, ce sera alors le crime parfait…','2010-11-21',
'Science Fiction de Christopher Nolan avec Ellen Page, Leonardo Di Caprio, Marion Cotillard...',0.76,'img10.jpg');
insert into FILMS (TITRE,DUREE,RESUME,DATESORTIE,ACTEUR,POPULARITE,IMAGE)values('The Green Hornet','1:58:00','Cette comédie délirante met en scène un super-héros pas comme les autres : Britt Reid, patron de presse le jour, redresseur de torts la nuit. Né dans les années trente dans une série radiophonique, le Frelon Vert prend un sacré coup de jeune devant la caméra du Michel Gondry. Plus connu pour ses films art et essai, le réalisateur travaille pour la première fois à Hollywood et livre sa vision 3D d’un personnage lui aussi très atypique dans le Panthéon des héros.','2011-03-11',
'Action de Michel Gondry avec Cameron Diaz, Jay Chou, Seth Rogen...',0,'img11.jpg');
insert into FILMS (TITRE,DUREE,RESUME,DATESORTIE,ACTEUR,POPULARITE,IMAGE)values('Y Tu Mama También','1:46:00','Les vies de Julio et Tenoch, deux adolescents de 17 ans, sont régies par leurs hormones, leur amitié et la vitesse précipitée avec laquelle ils cherchent à passer à l''âge adulte. Au cours d''un après-midi de fête familiale, ils font la rencontre de Luisa, une Espagnole de 28 ans, et ne tardent pas à flirter avec. En plaisantant, ils l''invitent à les accompagner en voiture sur une plage sauvage appelée la Boca del cielo, sans lui dire où elle se situe, ni même si elle existe vraiment. Luisa les ignore aimablement, ils prennent des routes différentes, l''incident est rapidement oublié. Cependant, celle-ci reçoit des nouvelles dévastatrices. Devant la nécessité d''un changement dans sa vie, elle retrouve les garçons et accepte leur offre.','2001-03-10',
'Non défini de Alfonso Cuarón avec Diego Luna, Gael García Bernal, Maribel Verdú...',0.22,'img12.jpg');
insert into FILMS (TITRE,DUREE,RESUME,DATESORTIE,ACTEUR,POPULARITE,IMAGE)values('Le fils à Jo','1:35:00','Chez les Canavaro, on est rugbyman de père en fils. Normal donc que Jo, ex-champion du club de Doumiac, pousse son fils de 13 ans à perpétuer la tradition familiale. Mais Jo, qui élève seul Tom depuis la mort de sa femme, se montre un peu trop protecteur sur le terrain, hurlant des conseils à chaque match et n’hésitant pas à en venir aux mains si les décisions de l’arbitre ne lui plaisent pas. De quoi faire honte à son fiston, qui ne fait aucun effort pour faire honneur à son père. Lorsque Tom décide de raccrocher les crampons, Jo va tout faire pour lui redonner le goût du jeu… L’ancien joueur de rugby Philippe Guillard marque un joli essai avec cette comédie où l’on trouve dans la mêlée drôlerie, tendresse et rudesse. « Il s’agit d’amour. Celui d’un père maladroit, qui ne comprend pas son garçon. Et celui, fraternel, de mecs sans famille, unis et réunis par le rugby », explique le réalisateur. Gérard Lanvin retrouve un personnage de bourru au grand cœur. Les personnages secondaires déploient aussi un joli jeu : Vincent Moscato est émouvant dans le rôle de Pompon, gentil garçon un peu simple. Olivier Marchal, lui, quitte le registre du film noir et se montre à l’aise en macho roublard et hâbleur.','2011-03-03',
'Comédie de Philippe Guillard avec Gérard Lanvin, Karina Lombard, Olivier Marchal...',0.3,'img13.jpg');
insert into FILMS (TITRE,DUREE,RESUME,DATESORTIE,ACTEUR,POPULARITE,IMAGE)values('Le Dernier des Templiers','1:33:00','Après des années de croisade en Terre sainte, le templier Behmen et son fidèle compagnon, Felson, reviennent en Europe, désabusés. Alors qu''ils aspirent à une vie paisible, ils découvrent leur pays ravagé par la peste noire et se retrouvent appréhendés par les hommes du Cardinal. Accusés d''avoir déserté, ils risquent la prison. Ils n''ont pas d''autre choix que d''accepter une étrange mission. Ils doivent escorter une mystérieuse jeune femme, désignée comme une sorcière responsable de l''épidémie, jusqu''à un lointain monastère où elle sera jugée et où sera pratiqué un ancestral rituel purificateur... À travers des terres hostiles et dévastées par la maladie, dans des contrées sauvages, Behmen, Felson et quelques autres, se lancent dans le plus dangereux et le plus fascinant de tous les périples. Alors qu''aux yeux de Behmen, la jeune femme apparaît de plus en plus comme un bouc émissaire, d''étranges phénomènes se produisent. Tous ne vont pas tarder à découvrir les effroyables forces qui les attendent...','2011-03-01',
'Aventure de Dominic Sena avec Nicolas Cage, Ron Perlman, Stephen Campbell Moore..',0,'img14.jpg')

