INSERT into RESERVATIONS(SEANCEID,TYPECARTEID, CARTEABONNEID) VALUES (6, 1,6);
INSERT into RESERVATIONS(SEANCEID,TYPECARTEID, CARTEABONNEID) VALUES (8,4,NULL);
INSERT into RESERVATIONS(SEANCEID,TYPECARTEID, CARTEABONNEID) VALUES (5,2,NULL);
INSERT into RESERVATIONS(SEANCEID,TYPECARTEID, CARTEABONNEID) VALUES (1,1,NULL);
INSERT into RESERVATIONS(SEANCEID,TYPECARTEID, CARTEABONNEID) VALUES (11,1,NULL);
INSERT into RESERVATIONS(SEANCEID,TYPECARTEID, CARTEABONNEID) VALUES (6,3,7);
INSERT into RESERVATIONS(SEANCEID,TYPECARTEID, CARTEABONNEID) VALUES (4,2,NULL);
INSERT into RESERVATIONS(SEANCEID,TYPECARTEID, CARTEABONNEID) VALUES (3,2,NULL);
INSERT into RESERVATIONS(SEANCEID,TYPECARTEID, CARTEABONNEID) VALUES (6,1,5);
