INSERT INTO TYPECARTES( NOM, TARIF) VALUES ('jeune',5);
INSERT INTO TYPECARTES( NOM, TARIF) VALUES ('etudiant',5);
INSERT INTO TYPECARTES( NOM, TARIF) VALUES ('abonne',6);
INSERT INTO TYPECARTES( NOM, TARIF) VALUES ('famille',7);
INSERT INTO TYPECARTES( NOM, TARIF) VALUES ('militaire',5);
INSERT INTO TYPECARTES( NOM, TARIF) VALUES ('chomeure',5);